"""Pydantic models for AEGIS API request/response types."""

from aegis.models.judge import (
    JudgeBatchRequest,
    JudgeOptions,
    JudgeRequest,
    JudgeResponse,
    JudgeStreamEvent,
    Risk,
    DefenseLayer,
)
from aegis.models.rules import (
    Rule,
    RuleCreateRequest,
    RuleTestRequest,
    RuleTestResponse,
    RuleUpdateRequest,
)
from aegis.models.escalations import (
    Escalation,
    EscalationCreateRequest,
    EscalationResolveRequest,
    EscalationStats,
)
from aegis.models.analytics import (
    AnalyticsOverview,
    AnalyticsQuery,
)
from aegis.models.evidence import Evidence, EvidenceVerification
from aegis.models.ml import (
    ClassifyRequest,
    ClassifyResponse,
    EmbedBatchRequest,
    EmbedRequest,
    EmbedResponse,
    SimilarityRequest,
    SimilarityResponse,
)
from aegis.models.classify import (
    ContentClassifyRequest,
    ContentClassifyResponse,
    ClassifyCategory,
)
from aegis.models.safety import SafetyCheckRequest, SafetyCheckResponse, SafetyCategory
from aegis.models.defense import (
    PaladinStats,
    TrustValidateRequest,
    TrustValidateResponse,
    TrustProfile,
    RagDetectRequest,
    RagDetectResponse,
    CircuitBreakerEvalRequest,
    CircuitBreakerResponse,
    CircuitBreakerStatus,
    AdaptiveEvalRequest,
    AdaptiveEvalResponse,
)
from aegis.models.jailbreak import (
    JailbreakDetectRequest,
    JailbreakDetectResponse,
    JailbreakType,
)
from aegis.models.advanced import AdvancedDetectRequest, AdvancedDetectResponse
from aegis.models.adversaflow import AttackCampaign, AttackRecord, AttackTrace
from aegis.models.agent import (
    AgentScanRequest,
    AgentScanResponse,
    ToolchainRequest,
    ToolchainResponse,
)
from aegis.models.anomaly import (
    AnomalyAlgorithm,
    AnomalyDetectRequest,
    AnomalyDetectResponse,
    AnomalyEvent,
    AnomalyStats,
)
from aegis.models.multimodal import (
    MultimodalScanRequest,
    MultimodalScanResponse,
)
from aegis.models.evolution import (
    EvolutionGenerateRequest,
    EvolutionGenerateResponse,
    EvolutionStats,
)
from aegis.models.saber import (
    SaberEstimateRequest,
    SaberEstimateResponse,
    SaberEvaluateRequest,
    SaberEvaluateResponse,
    SaberBudget,
    SaberCompareRequest,
    SaberCompareResponse,
)
from aegis.models.ai_act import (
    WatermarkRequest,
    WatermarkResponse,
    ComplianceVerifyRequest,
    ComplianceVerifyResponse,
    PiiDetectRequest,
    PiiDetectResponse,
    RiskAssessRequest,
    RiskAssessResponse,
    GuardrailCheckRequest,
    GuardrailCheckResponse,
)
from aegis.models.ops import (
    CiGateRequest,
    CiGateResponse,
    BenchmarkResult,
    RedTeamStats,
    AttackLibraryEntry,
)
from aegis.models.api_keys import ApiKey, ApiKeyCreateRequest, ApiKeyCreateResponse

__all__ = [
    "JudgeRequest",
    "JudgeResponse",
    "JudgeBatchRequest",
    "JudgeStreamEvent",
    "JudgeOptions",
    "Risk",
    "DefenseLayer",
    "Rule",
    "RuleCreateRequest",
    "RuleUpdateRequest",
    "RuleTestRequest",
    "RuleTestResponse",
    "Escalation",
    "EscalationCreateRequest",
    "EscalationResolveRequest",
    "EscalationStats",
    "AnalyticsOverview",
    "AnalyticsQuery",
    "Evidence",
    "EvidenceVerification",
    "EmbedRequest",
    "EmbedResponse",
    "EmbedBatchRequest",
    "ClassifyRequest",
    "ClassifyResponse",
    "SimilarityRequest",
    "SimilarityResponse",
    "ContentClassifyRequest",
    "ContentClassifyResponse",
    "ClassifyCategory",
    "SafetyCheckRequest",
    "SafetyCheckResponse",
    "SafetyCategory",
    "PaladinStats",
    "TrustValidateRequest",
    "TrustValidateResponse",
    "TrustProfile",
    "RagDetectRequest",
    "RagDetectResponse",
    "CircuitBreakerEvalRequest",
    "CircuitBreakerResponse",
    "CircuitBreakerStatus",
    "AdaptiveEvalRequest",
    "AdaptiveEvalResponse",
    "JailbreakDetectRequest",
    "JailbreakDetectResponse",
    "JailbreakType",
    "AdvancedDetectRequest",
    "AdvancedDetectResponse",
    "AttackCampaign",
    "AttackRecord",
    "AttackTrace",
    "AgentScanRequest",
    "AgentScanResponse",
    "ToolchainRequest",
    "ToolchainResponse",
    "AnomalyAlgorithm",
    "AnomalyDetectRequest",
    "AnomalyDetectResponse",
    "AnomalyEvent",
    "AnomalyStats",
    "MultimodalScanRequest",
    "MultimodalScanResponse",
    "EvolutionGenerateRequest",
    "EvolutionGenerateResponse",
    "EvolutionStats",
    "SaberEstimateRequest",
    "SaberEstimateResponse",
    "SaberEvaluateRequest",
    "SaberEvaluateResponse",
    "SaberBudget",
    "SaberCompareRequest",
    "SaberCompareResponse",
    "WatermarkRequest",
    "WatermarkResponse",
    "ComplianceVerifyRequest",
    "ComplianceVerifyResponse",
    "PiiDetectRequest",
    "PiiDetectResponse",
    "RiskAssessRequest",
    "RiskAssessResponse",
    "GuardrailCheckRequest",
    "GuardrailCheckResponse",
    "CiGateRequest",
    "CiGateResponse",
    "BenchmarkResult",
    "RedTeamStats",
    "AttackLibraryEntry",
    "ApiKey",
    "ApiKeyCreateRequest",
    "ApiKeyCreateResponse",
]
